// 英検2級単語リスト
// このリストにご自身で単語を追加していくことで、クイズの問題を増やすことができます。
const wordList = [
    // A
    { word: "を捨てる；を放棄する", choices: ["abandon", "absorb", "abuse", "accept"], answer: "abandon", example: { en: "They had to abandon the sinking ship.", ja: "彼らは沈みゆく船を放棄しなければならなかった。" } },
    { word: "能力", choices: ["ability", "absence", "access", "accident"], answer: "ability", example: { en: "She has the ability to solve complex problems.", ja: "彼女には複雑な問題を解決する能力がある。" } },
    { word: "～できる", choices: ["able", "about", "above", "abroad"], answer: "able", example: { en: "Are you able to join the meeting tomorrow?", ja: "明日、会議に参加できますか？" } },
    { word: "を吸収する", choices: ["absorb", "abuse", "accept", "accompany"], answer: "absorb", example: { en: "A sponge can absorb a lot of water.", ja: "スポンジはたくさんの水を吸収することができる。" } },
    { word: "を乱用する；を虐待する", choices: ["abuse", "accept", "accompany", "account"], answer: "abuse", example: { en: "He began to abuse alcohol after he lost his job.", ja: "彼は仕事を失ってからアルコールを乱用し始めた。" } },
    { word: "学術的な", choices: ["academic", "academy", "accent", "accident"], answer: "academic", example: { en: "She has an excellent academic record.", ja: "彼女は優秀な学業成績を収めている。" } },
    { word: "を受け入れる", choices: ["accept", "except", "access", "expect"], answer: "accept", example: { en: "Please accept my sincere apologies.", ja: "心からのお詫びを受け入れてください。" } },
    { word: "利用；アクセス", choices: ["access", "excess", "success", "assess"], answer: "access", example: { en: "You need a password to get access to the system.", ja: "そのシステムにアクセスするにはパスワードが必要です。" } },
    { word: "に同行する", choices: ["accompany", "accomplish", "account", "accumulate"], answer: "accompany", example: { en: "I will accompany you to the station.", ja: "駅までご一緒します。" } },
    { word: "を成し遂げる", choices: ["accomplish", "accompany", "publish", "punish"], answer: "accomplish", example: { en: "It's amazing what you can accomplish through teamwork.", ja: "チームワークを通じて達成できることには驚かされます。" } },
    { word: "（～の）せいである；説明する", choices: ["account", "amount", "count", "announce"], answer: "account", example: { en: "Human error accounted for the accident.", ja: "人為的ミスがその事故の原因だった。" } },
    { word: "正確な", choices: ["accurate", "acute", "active", "actual"], answer: "accurate", example: { en: "We need accurate information to make a decision.", ja: "決定を下すためには正確な情報が必要です。" } },
    { word: "を非難する", choices: ["accuse", "excuse", "abuse", "amuse"], answer: "accuse", example: { en: "He was accused of stealing money from the company.", ja: "彼は会社から金を盗んだとして告発された。" } },
    { word: "を達成する", choices: ["achieve", "believe", "relieve", "receive"], answer: "achieve", example: { en: "She worked hard to achieve her dream.", ja: "彼女は夢を達成するために一生懸命働いた。" } },
    { word: "を認める", choices: ["acknowledge", "knowledge", "acquaint", "acquire"], answer: "acknowledge", example: { en: "He acknowledged that he had made a mistake.", ja: "彼は間違いを犯したことを認めた。" } },
    { word: "を得る；を習得する", choices: ["acquire", "inquire", "require", "admire"], answer: "acquire", example: { en: "He acquired the skills needed for the job.", ja: "彼はその仕事に必要な技術を習得した。" } },
    { word: "活動的な", choices: ["active", "native", "actual", "actor"], answer: "active", example: { en: "It's important to stay active as you get older.", ja: "年をとっても活動的でいることは重要です。" } },
    { word: "実際の", choices: ["actual", "factual", "natural", "virtual"], answer: "actual", example: { en: "The actual cost was higher than the estimate.", ja: "実際の費用は見積もりよりも高かった。" } },
    { word: "を適応させる", choices: ["adapt", "adopt", "addict", "adept"], answer: "adapt", example: { en: "You need to adapt to the new environment.", ja: "あなたは新しい環境に適応する必要がある。" } },
    { word: "を加える", choices: ["add", "aid", "ad", "act"], answer: "add", example: { en: "Please add my name to the list.", ja: "私の名前をリストに加えてください。" } },
    { word: "を調節する", choices: ["adjust", "justify", "judge", "admit"], answer: "adjust", example: { en: "You can adjust the height of the driver's seat.", ja: "運転席の高さを調節できます。" } },
    { word: "管理", choices: ["administration", "admission", "admiration", "advertisement"], answer: "administration", example: { en: "He works in the sales administration department.", ja: "彼は販売管理部で働いている。" } },
    { word: "を賞賛する", choices: ["admire", "admit", "desire", "inspire"], answer: "admire", example: { en: "I admire his dedication to his work.", ja: "私は彼の仕事への献身を賞賛します。" } },
    { word: "を認める", choices: ["admit", "submit", "commit", "permit"], answer: "admit", example: { en: "She admitted breaking the window.", ja: "彼女は窓を割ったことを認めた。" } },
    { word: "を採用する；を養子にする", choices: ["adopt", "adapt", "adept", "adult"], answer: "adopt", example: { en: "We decided to adopt a new marketing strategy.", ja: "私たちは新しいマーケティング戦略を採用することに決めた。" } },
    { word: "進歩した", choices: ["advanced", "advantaged", "adventured", "advertised"], answer: "advanced", example: { en: "This course is for advanced learners.", ja: "このコースは上級者向けです。" } },
    { word: "利点", choices: ["advantage", "adventure", "average", "damage"], answer: "advantage", example: { en: "Being tall is an advantage in basketball.", ja: "背が高いことはバスケットボールにおいて利点だ。" } },
    { word: "に忠告する", choices: ["advise", "devise", "revise", "arise"], answer: "advise", example: { en: "My doctor advised me to quit smoking.", ja: "医者は私に禁煙するように忠告した。" } },
    { word: "に影響を及ぼす", choices: ["affect", "effect", "infect", "defect"], answer: "affect", example: { en: "The lack of rain affected the crops.", ja: "雨不足が作物に影響を与えた。" } },
    { word: "（～する）余裕がある", choices: ["afford", "effort", "avoid", "accord"], answer: "afford", example: { en: "We can't afford to buy a new house.", ja: "私たちに新しい家を買う余裕はない。" } },
    { word: "代理店", choices: ["agency", "agent", "agenda", "emergency"], answer: "agency", example: { en: "I booked my flight through a travel agency.", ja: "私は旅行代理店を通して航空便を予約した。" } },
    { word: "同意する", choices: ["agree", "degree", "eager", "argue"], answer: "agree", example: { en: "I agree with you on this point.", ja: "この点についてはあなたに同意します。" } },
    { word: "農業", choices: ["agriculture", "culture", "architecture", "furniture"], answer: "agriculture", example: { en: "Agriculture is the main industry in this region.", ja: "農業はこの地域の主要産業です。" } },
    { word: "援助", choices: ["aid", "aim", "air", "add"], answer: "aid", example: { en: "They sent humanitarian aid to the disaster area.", ja: "彼らは被災地に人道支援を送った。" } },
    { word: "警報", choices: ["alarm", "arm", "album", "calm"], answer: "alarm", example: { en: "The smoke alarm went off in the middle of the night.", ja: "夜中に煙探知機が鳴った。" } },
    { word: "を許す", choices: ["allow", "follow", "swallow", "hollow"], answer: "allow", example: { en: "Are pets allowed in this building?", ja: "この建物ではペットは許可されていますか？" } },
    { word: "ほとんど", choices: ["almost", "always", "among", "along"], answer: "almost", example: { en: "I'm almost finished with my report.", ja: "もうすぐレポートが仕上がります。" } },
    { word: "驚かせる", choices: ["amaze", "amuse", "abuse", "maze"], answer: "amaze", example: { en: "His magic tricks never fail to amaze me.", ja: "彼の手品にはいつも驚かされる。" } },
    { word: "野心", choices: ["ambition", "ammunition", "audition", "addition"], answer: "ambition", example: { en: "Her ambition is to become a famous singer.", ja: "彼女の野心は有名な歌手になることだ。" } },
    { word: "分析", choices: ["analysis", "analyst", "analogy", "anatomy"], answer: "analysis", example: { en: "Further analysis of the data is needed.", ja: "そのデータのさらなる分析が必要だ。" } },
    { word: "記念日", choices: ["anniversary", "annual", "universe", "necessary"], answer: "anniversary", example: { en: "We are celebrating our 10th wedding anniversary.", ja: "私たちは結婚10周年を祝っています。" } },
    { word: "不安；心配事", choices: ["anxiety", "variety", "society", "anger"], answer: "anxiety", example: { en: "He suffers from anxiety before exams.", ja: "彼は試験の前に不安に苦しむ。" } },
    { word: "訴え；魅力", choices: ["appeal", "appear", "apply", "applaud"], answer: "appeal", example: { en: "The charity made an appeal for donations.", ja: "その慈善団体は寄付を訴えかけた。" } },
    { word: "家電製品", choices: ["appliance", "application", "applicant", "appearance"], answer: "appliance", example: { en: "We need to buy some new kitchen appliances.", ja: "私たちは新しい台所用品をいくつか買う必要がある。" } },
    { word: "申し込み", choices: ["application", "implication", "publication", "explanation"], answer: "application", example: { en: "Have you filled out the application form?", ja: "申込用紙に記入しましたか？" } },
    { word: "を任命する", choices: ["appoint", "apply", "point", "disappoint"], answer: "appoint", example: { en: "She was appointed as the new chairperson.", ja: "彼女は新しい議長に任命された。" } },
    { word: "を正しく評価する；を感謝する", choices: ["appreciate", "appropriate", "approximate", "associate"], answer: "appreciate", example: { en: "I really appreciate all your help.", ja: "あなたのあらゆる助けに本当に感謝しています。" } },
    { word: "接近（法）", choices: ["approach", "broach", "reproach", "approximate"], answer: "approach", example: { en: "We need a new approach to solve this problem.", ja: "この問題を解決するためには新しいアプローチが必要だ。" } },
    { word: "適切な", choices: ["appropriate", "approximate", "appreciate", "approve"], answer: "appropriate", example: { en: "Please wear appropriate clothes for the occasion.", ja: "その場にふさわしい服装をしてください。" } },
    { word: "承認", choices: ["approval", "proposal", "removal", "arrival"], answer: "approval", example: { en: "The plan has been given official approval.", ja: "その計画は公式に承認された。" } },
    { word: "建築", choices: ["architecture", "agriculture", "archive", "adventure"], answer: "architecture", example: { en: "He is studying modern architecture at university.", ja: "彼は大学で現代建築を学んでいる。" } },
    { word: "生じる", choices: ["arise", "raise", "rise", "advise"], answer: "arise", example: { en: "A number of problems have arisen.", ja: "多くの問題が生じている。" } },
    { word: "を手配する", choices: ["arrange", "range", "orange", "exchange"], answer: "arrange", example: { en: "I'll arrange a taxi to the airport for you.", ja: "空港までのタクシーを手配します。" } },
    { word: "逮捕", choices: ["arrest", "rest", "forest", "interest"], answer: "arrest", example: { en: "The police made an arrest this morning.", ja: "警察は今朝、逮捕者を出した。" } },
    { word: "人工の", choices: ["artificial", "official", "article", "artistic"], answer: "artificial", example: { en: "This plant has artificial flowers.", ja: "この植物には造花がついている。" } },
    { word: "側面；観点", choices: ["aspect", "inspect", "respect", "suspect"], answer: "aspect", example: { en: "We must consider every aspect of the problem.", ja: "私たちは問題のあらゆる側面を考慮しなければならない。" } },
    { word: "を割り当てる", choices: ["assign", "design", "resign", "sign"], answer: "assign", example: { en: "The teacher assigned homework to the students.", ja: "先生は生徒に宿題を割り当てた。" } },
    { word: "と交際する；を連想する", choices: ["associate", "appreciate", "assist", "negotiate"], answer: "associate", example: { en: "He is known to associate with criminals.", ja: "彼は犯罪者と交際していることで知られている。" } },
    { word: "を引き受ける；と仮定する", choices: ["assume", "consume", "resume", "assure"], answer: "assume", example: { en: "I assume you have finished your work.", ja: "あなたは仕事を終えたものと思います。" } },
    { word: "を保証する", choices: ["assure", "ensure", "insure", "measure"], answer: "assure", example: { en: "I can assure you that this is a safe investment.", ja: "これが安全な投資であることを保証します。" } },
    { word: "驚くべき", choices: ["astonishing", "establishing", "punishing", "accompanying"], answer: "astonishing", example: { en: "She showed an astonishing talent for music.", ja: "彼女は音楽に対して驚くべき才能を示した。" } },
    { word: "雰囲気；大気", choices: ["atmosphere", "sphere", "hemisphere", "biosphere"], answer: "atmosphere", example: { en: "The hotel has a very relaxed atmosphere.", ja: "そのホテルはとてもリラックスした雰囲気だ。" } },
    { word: "を取り付ける；を添付する", choices: ["attach", "attack", "detach", "attain"], answer: "attach", example: { en: "I forgot to attach the file to the email.", ja: "メールにファイルを添付するのを忘れた。" } },
    { word: "を達成する", choices: ["attain", "contain", "maintain", "obtain"], answer: "attain", example: { en: "She attained the rank of professor.", ja: "彼女は教授の地位を達成した。" } },
    { word: "試み", choices: ["attempt", "attend", "tempt", "contempt"], answer: "attempt", example: { en: "It was a brave attempt to break the record.", ja: "それは記録を破るための勇敢な試みだった。" } },
    { word: "に出席する", choices: ["attend", "intend", "extend", "defend"], answer: "attend", example: { en: "All employees are required to attend the meeting.", ja: "全ての従業員は会議への出席が求められている。" } },
    { word: "弁護士", choices: ["attorney", "journey", "tourney", "chimney"], answer: "attorney", example: { en: "You should consult an attorney about this matter.", ja: "この件については弁護士に相談すべきです。" } },
    { word: "を引きつける", choices: ["attract", "contract", "distract", "abstract"], answer: "attract", example: { en: "The festival attracts thousands of visitors each year.", ja: "その祭りは毎年何千人もの観光客を引きつける。" } },
    { word: "に起因すると考える", choices: ["attribute", "contribute", "distribute", "tribute"], answer: "attribute", example: { en: "He attributed his success to hard work.", ja: "彼は自分の成功を勤勉の賜物と考えた。" } },
    { word: "利用できる", choices: ["available", "valuable", "avoidable", "achievable"], answer: "available", example: { en: "Are there any tickets available for tonight's show?", ja: "今夜のショーのチケットはありますか？" } },
    // B
    { word: "収支", choices: ["balance", "allowance", "lance", "chance"], answer: "balance", example: { en: "You need to check your bank balance regularly.", ja: "定期的に銀行の残高を確認する必要があります。" } },
    { word: "障壁；防壁", choices: ["barrier", "carrier", "barrel", "barber"], answer: "barrier", example: { en: "Language barriers can make communication difficult.", ja: "言葉の壁はコミュニケーションを困難にすることがある。" } },
    { word: "基本的に", choices: ["basically", "physically", "logically", "classically"], answer: "basically", example: { en: "Basically, my job is to answer customer emails.", ja: "基本的に、私の仕事は顧客のメールに返信することです。" } },
    { word: "電池", choices: ["battery", "battle", "bakery", "lottery"], answer: "battery", example: { en: "I need to change the battery in my watch.", ja: "腕時計の電池を交換する必要がある。" } },
    { word: "戦場", choices: ["battlefield", "field", "baseball", "battle"], answer: "battlefield", example: { en: "The battlefield was covered with smoke.", ja: "戦場は煙に覆われていた。" } },
    { word: "の他に；に加えて", choices: ["besides", "beside", "behind", "below"], answer: "besides", example: { en: "Besides English, she can speak French.", ja: "英語の他に、彼女はフランス語も話せる。" } },
    { word: "請求書；紙幣", choices: ["bill", "pill", "hill", "fill"], answer: "bill", example: { en: "Have you paid the electricity bill?", ja: "電気代の請求書は支払いましたか？" } },
    { word: "生物学", choices: ["biology", "biography", "geology", "psychology"], answer: "biology", example: { en: "She is studying biology at university.", ja: "彼女は大学で生物学を勉強している。" } },
    { word: "奇妙な", choices: ["bizarre", "bazaar", "blizzard", "buzzard"], answer: "bizarre", example: { en: "He told me a bizarre story.", ja: "彼は私に奇妙な話をした。" } },
    { word: "非難する", choices: ["blame", "flame", "name", "same"], answer: "blame", example: { en: "Don't blame others for your own mistakes.", ja: "自分の失敗を他人のせいにしないでください。" } },
    { word: "きずな；債券", choices: ["bond", "band", "pond", "fond"], answer: "bond", example: { en: "There is a strong bond between them.", ja: "彼らの間には強いきずながある。" } },
    { word: "を予約する", choices: ["book", "look", "cook", "hook"], answer: "book", example: { en: "I'd like to book a table for two.", ja: "2名でテーブルを予約したいのですが。" } },
    { word: "悩ます", choices: ["bother", "brother", "mother", "other"], answer: "bother", example: { en: "I'm sorry to bother you, but could you help me?", ja: "お邪魔してすみませんが、手伝っていただけますか？" } },
    { word: "枝；支店", choices: ["branch", "bench", "bunch", "ranch"], answer: "branch", example: { en: "A bird is singing on the branch of that tree.", ja: "鳥がその木の枝で歌っている。" } },
    { word: "ブランド；銘柄", choices: ["brand", "band", "grand", "land"], answer: "brand", example: { en: "This is a very popular brand of coffee.", ja: "これは非常に人気のあるコーヒーのブランドです。" } },
    { word: "簡潔な", choices: ["brief", "belief", "grief", "chief"], answer: "brief", example: { en: "Please give me a brief explanation.", ja: "簡潔な説明をお願いします。" } },
    { word: "放送する", choices: ["broadcast", "abroad", "road", "board"], answer: "broadcast", example: { en: "The concert will be broadcast live.", ja: "そのコンサートは生放送されます。" } },
    { word: "予算", choices: ["budget", "gadget", "bucket", "bullet"], answer: "budget", example: { en: "We need to stick to our budget.", ja: "私たちは予算を守る必要がある。" } },
    { word: "重荷", choices: ["burden", "button", "garden", "sudden"], answer: "burden", example: { en: "I don't want to be a burden to you.", ja: "あなたの重荷になりたくない。" } },
    // C
    { word: "内閣；戸棚", choices: ["cabinet", "cabin", "cable", "carpet"], answer: "cabinet", example: { en: "The prime minister formed a new cabinet.", ja: "総理大臣は新しい内閣を組織した。" } },
    { word: "候補者", choices: ["candidate", "candle", "candy", "captain"], answer: "candidate", example: { en: "There are three candidates for the position.", ja: "その役職には3人の候補者がいる。" } },
    { word: "能力", choices: ["capacity", "capability", "capital", "capture"], answer: "capacity", example: { en: "The stadium has a seating capacity of 50,000.", ja: "そのスタジアムの収容能力は5万人です。" } },
    { word: "捕らえる", choices: ["capture", "rapture", "captain", "sculpture"], answer: "capture", example: { en: "The police captured the escaped prisoner.", ja: "警察は脱獄囚を捕らえた。" } },
    { word: "貨物", choices: ["cargo", "car", "go", "logo"], answer: "cargo", example: { en: "The ship was carrying a cargo of oil.", ja: "その船は石油という貨物を運んでいた。" } },
    { word: "場合；事件", choices: ["case", "cause", "base", "chase"], answer: "case", example: { en: "In that case, you should call the police.", ja: "その場合は、警察に電話すべきです。" } },
    { word: "範疇", choices: ["category", "factory", "catalogue", "caterpillar"], answer: "category", example: { en: "The books are divided into different categories.", ja: "本は異なるカテゴリーに分けられている。" } },
    { word: "天井", choices: ["ceiling", "feeling", "sealing", "stealing"], answer: "ceiling", example: { en: "The ceiling of this room is very high.", ja: "この部屋の天井はとても高い。" } },
    { word: "儀式", choices: ["ceremony", "cemetery", "celery", "century"], answer: "ceremony", example: { en: "The wedding ceremony was held in a church.", ja: "結婚式は教会で行われた。" } },
    { word: "議長", choices: ["chairman", "chain", "chair", "hairman"], answer: "chairman", example: { en: "He was elected chairman of the committee.", ja: "彼は委員会の議長に選ばれた。" } },
    { word: "慈善（事業）", choices: ["charity", "character", "clarity", "parity"], answer: "charity", example: { en: "She donates a lot of money to charity.", ja: "彼女は慈善事業に多額の寄付をしている。" } },
    { word: "化学の", choices: ["chemical", "physical", "medical", "technical"], answer: "chemical", example: { en: "This factory produces industrial chemicals.", ja: "この工場は工業薬品を生産している。" } },
    { word: "状況", choices: ["circumstance", "distance", "instance", "substance"], answer: "circumstance", example: { en: "Under the circumstances, we have to cancel the trip.", ja: "このような状況下では、私たちは旅行を中止しなければならない。" } },
    { word: "文明", choices: ["civilization", "citizen", "civil", "organization"], answer: "civilization", example: { en: "The ancient Egyptian civilization lasted for thousands of years.", ja: "古代エジプト文明は何千年もの間続いた。" } },
    { word: "を明らかにする", choices: ["clarify", "classify", "certify", "terrify"], answer: "clarify", example: { en: "Could you clarify your last point?", ja: "最後の点を明確にしていただけますか？" } },
    { word: "依頼人", choices: ["client", "clinic", "clerk", "talent"], answer: "client", example: { en: "The company has many important clients.", ja: "その会社には多くの重要な顧客がいる。" } },
    { word: "同僚", choices: ["colleague", "college", "league", "collect"], answer: "colleague", example: { en: "I went out for a drink with my colleagues.", ja: "私は同僚たちと飲みに行った。" } },
    { word: "結合させる", choices: ["combine", "confine", "define", "decline"], answer: "combine", example: { en: "We should combine our efforts to succeed.", ja: "成功するためには私たちの努力を結合させるべきだ。" } },
    { word: "委員会", choices: ["committee", "community", "commit", "comment"], answer: "committee", example: { en: "The committee will meet next week.", ja: "委員会は来週開かれます。" } },
    { word: "比較する", choices: ["compare", "prepare", "repair", "despair"], answer: "compare", example: { en: "Don't compare yourself to others.", ja: "他人と自分を比較してはいけない。" } },
    { word: "構成する", choices: ["compose", "propose", "suppose", "expose"], answer: "compose", example: { en: "Water is composed of hydrogen and oxygen.", ja: "水は水素と酸素から構成されている。" } },
    { word: "を集中させる", choices: ["concentrate", "congratulate", "contemplate", "consecrate"], answer: "concentrate", example: { en: "I can't concentrate on my work with all this noise.", ja: "この騒音の中では仕事に集中できない。" } },
    { word: "行う", choices: ["conduct", "contact", "construct", "deduct"], answer: "conduct", example: { en: "The scientist will conduct an experiment.", ja: "その科学者は実験を行う予定だ。" } },
    { word: "会議", choices: ["conference", "confidence", "inference", "reference"], answer: "conference", example: { en: "I'm attending a conference in London next week.", ja: "私は来週ロンドンでの会議に出席します。" } },
    { word: "紛争；対立", choices: ["conflict", "inflict", "afflict", "strict"], answer: "conflict", example: { en: "The country has been in conflict for years.", ja: "その国は何年もの間、紛争状態にある。" } },
    { word: "意識", choices: ["consciousness", "conscience", "conscious", "consensus"], answer: "consciousness", example: { en: "He lost consciousness after the accident.", ja: "彼は事故の後、意識を失った。" } },
    { word: "保護", choices: ["conservation", "conversation", "observation", "preservation"], answer: "conservation", example: { en: "Conservation of wildlife is very important.", ja: "野生生物の保護は非常に重要です。" } },
    { word: "（～から）成る", choices: ["consist", "insist", "persist", "resist"], answer: "consist", example: { en: "The team consists of ten members.", ja: "そのチームは10人のメンバーで構成されている。" } },
    { word: "絶え間ない", choices: ["constant", "distant", "instant", "consistent"], answer: "constant", example: { en: "The machine needs constant attention.", ja: "その機械は絶え間ない注意が必要だ。" } },
    { word: "消費者", choices: ["consumer", "customer", "producer", "supplier"], answer: "consumer", example: { en: "Consumer demand for organic food is increasing.", ja: "有機食品に対する消費者の需要は増加している。" } },
    { word: "文脈；状況", choices: ["context", "contest", "contact", "content"], answer: "context", example: { en: "You should consider the context of the sentence.", ja: "あなたはその文の文脈を考慮すべきです。" } },
    { word: "大陸", choices: ["continent", "content", "continue", "contingent"], answer: "continent", example: { en: "Africa is a very large continent.", ja: "アフリカは非常に大きな大陸だ。" } },
    { word: "契約", choices: ["contract", "contact", "contrast", "attract"], answer: "contract", example: { en: "Please read the contract carefully before you sign.", ja: "署名する前に契約書を注意深く読んでください。" } },
    { word: "対照", choices: ["contrast", "contact", "contract", "construct"], answer: "contrast", example: { en: "There is a sharp contrast between the two sisters.", ja: "その姉妹の間には著しい対照がある。" } },
    { word: "便利な", choices: ["convenient", "conventional", "content", "confident"], answer: "convenient", example: { en: "The new supermarket is very convenient for me.", ja: "新しいスーパーマーケットは私にとって非常に便利だ。" } },
    { word: "説得する", choices: ["convince", "convene", "convey", "convict"], answer: "convince", example: { en: "I managed to convince him to join our team.", ja: "私は彼を説得して私たちのチームに参加させた。" } },
    { word: "協力する", choices: ["cooperate", "operate", "corporate", "compare"], answer: "cooperate", example: { en: "We must all cooperate to finish this project.", ja: "このプロジェクトを終えるために私たちは皆協力しなければならない。" } }
];
