// 英検2級単語リスト
// このリストに単語を追加していくことで、クイズの問題を増やすことができます。
// 形式: { word: "日本語訳", answer: "英単語", choices: ["選択肢1", "選択肢2", "選択肢3", "選択肢4"], example: { en: "英語の例文", ja: "例文の日本語訳" } }

const wordList = [
    { word: "を捨てる；を放棄する", choices: ["abandon", "absorb", "abuse", "accept"], answer: "abandon", example: { en: "They had to abandon the sinking ship.", ja: "彼らは沈みゆく船を放棄しなければならなかった。" } },
    { word: "を吸収する", choices: ["absorb", "abuse", "accept", "accompany"], answer: "absorb", example: { en: "A sponge can absorb a lot of water.", ja: "スポンジはたくさんの水を吸収することができる。" } },
    { word: "を乱用する；を虐待する", choices: ["abuse", "accept", "accompany", "account"], answer: "abuse", example: { en: "He began to abuse alcohol after he lost his job.", ja: "彼は仕事を失ってからアルコールを乱用し始めた。" } },
    { word: "を受け入れる", choices: ["accept", "accompany", "account", "accuse"], answer: "accept", example: { en: "I accept your apology.", ja: "私はあなたの謝罪を受け入れます。" } },
    { word: "に同行する；に付随して起こる", choices: ["accompany", "account", "accuse", "achieve"], answer: "accompany", example: { en: "Children must be accompanied by an adult.", ja: "子供は大人の同伴が必要です。" } },
    { word: "説明する；（の）原因となる", choices: ["account", "accuse", "achieve", "acquire"], answer: "account", example: { en: "His reckless driving accounted for the accident.", ja: "彼の無謀な運転がその事故の原因だった。" } },
    { word: "を非難する；を告訴する", choices: ["accuse", "achieve", "acquire", "act"], answer: "accuse", example: { en: "She accused him of stealing her money.", ja: "彼女は彼がお金を盗んだと非難した。" } },
    { word: "を達成する", choices: ["achieve", "acquire", "act", "adapt"], answer: "achieve", example: { en: "He worked hard to achieve his goal.", ja: "彼は目標を達成するために一生懸命働いた。" } },
    { word: "を得る；を習得する", choices: ["acquire", "act", "adapt", "add"], answer: "acquire", example: { en: "She acquired a good knowledge of English.", ja: "彼女は英語の十分な知識を習得した。" } },
    { word: "行動する；を演じる", choices: ["act", "adapt", "add", "adjust"], answer: "act", example: { en: "You must act quickly to solve the problem.", ja: "その問題を解決するためには迅速に行動しなければならない。" } },
    { word: "を適応させる；適応する", choices: ["adapt", "add", "adjust", "admire"], answer: "adapt", example: { en: "Animals have to adapt to their environment.", ja: "動物は環境に適応しなければならない。" } },
    { word: "を加える", choices: ["add", "adjust", "admire", "admit"], answer: "add", example: { en: "Please add some sugar to my coffee.", ja: "私のコーヒーに砂糖を少し加えてください。" } },
    { word: "を調節する；適合させる", choices: ["adjust", "admire", "admit", "adopt"], answer: "adjust", example: { en: "You can adjust the height of the chair.", ja: "椅子の高さを調節できます。" } },
    { word: "に感心する；を賞賛する", choices: ["admire", "admit", "adopt", "advance"], answer: "admire", example: { en: "I admire her for her courage.", ja: "私は彼女の勇気に感心する。" } },
    { word: "を（事実・妥当だと）認める", choices: ["admit", "adopt", "advance", "advertise"], answer: "admit", example: { en: "He admitted his mistake.", ja: "彼は自分の間違いを認めた。" } },
    { word: "を採用する；を養子にする", choices: ["adopt", "advance", "advertise", "advise"], answer: "adopt", example: { en: "The company decided to adopt a new policy.", ja: "その会社は新しい方針を採用することを決定した。" } },
    { word: "前進する；を進める", choices: ["advance", "advertise", "advise", "affect"], answer: "advance", example: { en: "Technology has advanced rapidly.", ja: "科学技術は急速に進歩した。" } },
    { word: "を宣伝する", choices: ["advertise", "advise", "affect", "afford"], answer: "advertise", example: { en: "They advertised their new product on TV.", ja: "彼らは新製品をテレビで宣伝した。" } },
    { word: "に忠告する", choices: ["advise", "affect", "afford", "agree"], answer: "advise", example: { en: "My doctor advised me to get more exercise.", ja: "医者は私にもっと運動するように忠告した。" } },
    { word: "に影響を与える", choices: ["affect", "afford", "agree", "aim"], answer: "affect", example: { en: "Lack of sleep can affect your performance.", ja: "睡眠不足はあなたの成績に影響を与える可能性がある。" } },
    { word: "（～する）余裕がある", choices: ["afford", "agree", "aim", "allow"], answer: "afford", example: { en: "I can't afford to buy a new car.", ja: "私には新車を買う余裕がない。" } },
    { word: "賛成する；同意する", choices: ["agree", "aim", "allow", "announce"], answer: "agree", example: { en: "I agree with your opinion.", ja: "私はあなたの意見に賛成です。" } },
    { word: "をねらう；目指す", choices: ["aim", "allow", "announce", "apologize"], answer: "aim", example: { en: "He is aiming to become a professional soccer player.", ja: "彼はプロのサッカー選手になることを目指している。" } },
    { word: "を許す", choices: ["allow", "announce", "apologize", "appeal"], answer: "allow", example: { en: "Smoking is not allowed in this building.", ja: "この建物内では喫煙は許可されていません。" } },
    { word: "を発表する", choices: ["announce", "apologize", "appeal", "appear"], answer: "announce", example: { en: "The government will announce the new plan tomorrow.", ja: "政府は明日、新しい計画を発表するだろう。" } },
    { word: "を予想する；を期待する", choices: ["anticipate", "apologize", "appeal", "appear"], answer: "anticipate", example: { en: "We anticipate that the project will be successful.", ja: "私たちはそのプロジェクトが成功すると予想している。" } },
    { word: "謝る", choices: ["apologize", "appeal", "appear", "apply"], answer: "apologize", example: { en: "You should apologize for what you said.", ja: "あなたは自分の言ったことについて謝るべきだ。" } },
    { word: "訴える；抗議する", choices: ["appeal", "appear", "apply", "appoint"], answer: "appeal", example: { en: "The design of the car appeals to young people.", ja: "その車のデザインは若者に訴えかける。" } },
    { word: "現れる；～のように見える", choices: ["appear", "apply", "appoint", "appreciate"], answer: "appear", example: { en: "A ship appeared on the horizon.", ja: "船が地平線に現れた。" } },
    { word: "申し込む；を適用する", choices: ["apply", "appoint", "appreciate", "approach"], answer: "apply", example: { en: "I decided to apply for the job.", ja: "私はその仕事に応募することに決めた。" } },
    { word: "を任命する；（時・場所）を指定する", choices: ["appoint", "appreciate", "approach", "approve"], answer: "appoint", example: { en: "The company appointed him as the new manager.", ja: "会社は彼を新しいマネージャーに任命した。" } },
    { word: "を正しく評価する；を感謝する", choices: ["appreciate", "approach", "approve", "argue"], answer: "appreciate", example: { en: "I really appreciate your help.", ja: "あなたの助けに本当に感謝しています。" } },
    { word: "に近づく", choices: ["approach", "approve", "argue", "arise"], answer: "approach", example: { en: "Winter is approaching.", ja: "冬が近づいている。" } },
    { word: "に賛成する；を承認する", choices: ["approve", "argue", "arise", "arrange"], answer: "approve", example: { en: "My parents do not approve of my plan.", ja: "私の両親は私の計画に賛成していない。" } },
    { word: "と主張する；を議論する", choices: ["argue", "arise", "arrange", "arrest"], answer: "argue", example: { en: "They argued about politics for hours.", ja: "彼らは何時間も政治について議論した。" } },
    { word: "生じる", choices: ["arise", "arrange", "arrest", "arrive"], answer: "arise", example: { en: "A new problem has arisen.", ja: "新しい問題が生じた。" } },
    { word: "を手配する；を整理する", choices: ["arrange", "arrest", "arrive", "ask"], answer: "arrange", example: { en: "Can you arrange a meeting for next week?", ja: "来週の会議を手配してもらえますか？" } },
    { word: "を逮捕する", choices: ["arrest", "arrive", "ask", "assist"], answer: "arrest", example: { en: "The police arrested the suspect.", ja: "警察は容疑者を逮捕した。" } },
    { word: "到着する", choices: ["arrive", "ask", "assist", "associate"], answer: "arrive", example: { en: "What time will the train arrive?", ja: "その電車は何時に到着しますか？" } },
    { word: "を尋ねる；を頼む", choices: ["ask", "assist", "associate", "assume"], answer: "ask", example: { en: "Can I ask you a question?", ja: "質問してもいいですか？" } },
    { word: "を助ける", choices: ["assist", "associate", "assume", "assure"], answer: "assist", example: { en: "He assisted her with her bags.", ja: "彼は彼女のバッグを持つのを手伝った。" } },
    { word: "を連想する；と交際する", choices: ["associate", "assume", "assure", "attach"], answer: "associate", example: { en: "I always associate this song with my childhood.", ja: "私はいつもこの歌を子供時代と結びつけて考える。" } },
    { word: "と思い込む；を引き受ける", choices: ["assume", "assure", "attach", "attack"], answer: "assume", example: { en: "I assume you know what you are doing.", ja: "あなたは自分が何をしているか分かっていると思います。" } },
    { word: "を保証する；を安心させる", choices: ["assure", "attach", "attack", "attain"], answer: "assure", example: { en: "I can assure you that you will be safe.", ja: "あなたが安全であることを保証します。" } },
    { word: "を付ける；を添付する", choices: ["attach", "attack", "attain", "attempt"], answer: "attach", example: { en: "Please attach the file to your email.", ja: "Eメールにファイルを添付してください。" } },
    { word: "を攻撃する", choices: ["attack", "attain", "attempt", "attend"], answer: "attack", example: { en: "The army attacked the enemy at dawn.", ja: "軍は夜明けに敵を攻撃した。" } },
    { word: "を達成する；を獲得する", choices: ["attain", "attempt", "attend", "attract"], answer: "attain", example: { en: "She attained her goal of becoming a lawyer.", ja: "彼女は弁護士になるという目標を達成した。" } },
    { word: "を試みる", choices: ["attempt", "attend", "attract", "avoid"], answer: "attempt", example: { en: "He attempted to break the world record.", ja: "彼は世界記録を破ろうと試みた。" } },
    { word: "に出席する；の世話をする", choices: ["attend", "attract", "avoid", "await"], answer: "attend", example: { en: "Are you going to attend the meeting?", ja: "あなたはその会議に出席しますか？" } },
    { word: "を引きつける", choices: ["attract", "avoid", "await", "award"], answer: "attract", example: { en: "The beautiful garden attracts many tourists.", ja: "その美しい庭は多くの観光客を引きつける。" } },
    { word: "を避ける", choices: ["avoid", "await", "award", "ban"], answer: "avoid", example: { en: "You should avoid eating too much junk food.", ja: "ジャンクフードの食べ過ぎは避けるべきだ。" } },
    { word: "を待つ", choices: ["await", "award", "ban", "bear"], answer: "await", example: { en: "A surprise awaits you in the next room.", ja: "次の部屋で驚きがあなたを待っています。" } },
    { word: "を授与する", choices: ["award", "ban", "bear", "beat"], answer: "award", example: { en: "She was awarded the Nobel Prize for her discovery.", ja: "彼女はその発見に対してノーベル賞を授与された。" } },
    { word: "を禁止する", choices: ["ban", "bear", "beat", "behave"], answer: "ban", example: { en: "The city has banned smoking in public places.", ja: "その市は公共の場所での喫煙を禁止した。" } },
    { word: "を我慢する；を産む；を身につける", choices: ["bear", "beat", "behave", "belong"], answer: "bear", example: { en: "I can't bear the pain.", ja: "私はその痛みに耐えられない。" } },
    { word: "を打つ；を打ち負かす", choices: ["beat", "behave", "belong", "bend"], answer: "beat", example: { en: "Our team beat the champions.", ja: "私たちのチームはチャンピオンを打ち負かした。" } },
    { word: "振る舞う", choices: ["behave", "belong", "bend", "bet"], answer: "behave", example: { en: "You must behave yourself in front of guests.", ja: "お客様の前では行儀よくしなければなりません。" } },
    { word: "に属する", choices: ["belong", "bend", "bet", "blame"], answer: "belong", example: { en: "This book belongs to the library.", ja: "この本は図書館のものです。" } },
    { word: "を曲げる", choices: ["bend", "bet", "blame", "blow"], answer: "bend", example: { en: "Can you bend this wire?", ja: "このワイヤーを曲げられますか？" } },
    { word: "を賭ける", choices: ["bet", "blame", "blow", "boil"], answer: "bet", example: { en: "I bet he will be late.", ja: "彼はきっと遅刻すると思うよ。" } },
    { word: "を非難する；のせいにする", choices: ["blame", "blow", "boil", "borrow"], answer: "blame", example: { en: "Don't blame me for your mistakes.", ja: "あなたの失敗を私のせいにしないでください。" } },
    { word: "（風が）吹く；を吹き飛ばす", choices: ["blow", "boil", "borrow", "bother"], answer: "blow", example: { en: "The wind is blowing hard today.", ja: "今日は風が強く吹いている。" } },
    { word: "を沸かす；煮る", choices: ["boil", "borrow", "bother", "break"], answer: "boil", example: { en: "Could you boil some water for tea?", ja: "お茶のためにお湯を沸かしてくれませんか？" } },
    { word: "を借りる", choices: ["borrow", "bother", "break", "breathe"], answer: "borrow", example: { en: "Can I borrow your pen?", ja: "あなたのペンを借りてもいいですか？" } },
    { word: "を悩ませる", choices: ["bother", "break", "breathe", "bring"], answer: "bother", example: { en: "Sorry to bother you, but I have a question.", ja: "お邪魔してすみませんが、質問があります。" } },
    { word: "を壊す；を破る", choices: ["break", "breathe", "bring", "build"], answer: "break", example: { en: "Be careful not to break the glass.", ja: "ガラスを割らないように気をつけてください。" } },
    { word: "呼吸する", choices: ["breathe", "bring", "build", "burn"], answer: "breathe", example: { en: "It's important to breathe deeply when you exercise.", ja: "運動するときは深呼吸することが重要だ。" } },
    { word: "を持ってくる", choices: ["bring", "build", "burn", "burst"], answer: "bring", example: { en: "Please bring your textbook to class.", ja: "授業に教科書を持ってきてください。" } },
    { word: "を放送する", choices: ["broadcast", "build", "burn", "burst"], answer: "broadcast", example: { en: "The news will be broadcast at 7 p.m.", ja: "そのニュースは午後7時に放送されます。" } },
    { word: "を建てる", choices: ["build", "burn", "burst", "bury"], answer: "build", example: { en: "They are building a new bridge.", ja: "彼らは新しい橋を建設している。" } },
    { word: "を燃やす", choices: ["burn", "burst", "bury", "buy"], answer: "burn", example: { en: "The house burned down completely.", ja: "その家は全焼した。" } },
    { word: "破裂する", choices: ["burst", "bury", "buy", "calculate"], answer: "burst", example: { en: "The balloon burst with a loud bang.", ja: "風船が大きな音を立てて破裂した。" } },
    { word: "を埋める", choices: ["bury", "buy", "calculate", "call"], answer: "bury", example: { en: "They buried the treasure on the island.", ja: "彼らはその宝物を島に埋めた。" } },
    { word: "を買う", choices: ["buy", "calculate", "call", "cancel"], answer: "buy", example: { en: "I'm going to buy a new computer.", ja: "私は新しいコンピュータを買うつもりです。" } },
    { word: "を計算する", choices: ["calculate", "call", "cancel", "care"], answer: "calculate", example: { en: "Can you calculate the total cost?", ja: "総費用を計算できますか？" } },
    { word: "を呼ぶ；に電話する", choices: ["call", "cancel", "care", "carry"], answer: "call", example: { en: "I'll call you later.", ja: "後で電話します。" } },
    { word: "を取り消す", choices: ["cancel", "care", "carry", "catch"], answer: "cancel", example: { en: "The flight was canceled due to the storm.", ja: "その便は嵐のため欠航になった。" } },
    { word: "を気にする；の世話をする", choices: ["care", "carry", "catch", "cause"], answer: "care", example: { en: "She cares for her elderly parents.", ja: "彼女は年老いた両親の世話をしている。" } },
    { word: "を運ぶ", choices: ["carry", "catch", "cause", "celebrate"], answer: "carry", example: { en: "This bag is too heavy to carry.", ja: "このかばんは重すぎて運べない。" } },
    { word: "を捕まえる", choices: ["catch", "cause", "celebrate", "change"], answer: "catch", example: { en: "The cat tried to catch the mouse.", ja: "猫はネズミを捕まえようとした。" } },
    { word: "を引き起こす", choices: ["cause", "celebrate", "change", "charge"], answer: "cause", example: { en: "The heavy rain caused a flood.", ja: "大雨が洪水を起こした。" } },
    { word: "を祝う", choices: ["celebrate", "change", "charge", "chase"], answer: "celebrate", example: { en: "We are going to celebrate her birthday.", ja: "私たちは彼女の誕生日を祝うつもりです。" } },
    { word: "を変える", choices: ["change", "charge", "chase", "check"], answer: "change", example: { en: "You can't change the past.", ja: "過去は変えられない。" } },
    { word: "を請求する；を非難する；を充電する", choices: ["charge", "chase", "check", "choose"], answer: "charge", example: { en: "How much do you charge for this service?", ja: "このサービスの料金はいくらですか？" } },
    { word: "を追いかける", choices: ["chase", "check", "choose", "claim"], answer: "chase", example: { en: "The dog chased the cat across the yard.", ja: "犬は庭を横切って猫を追いかけた。" } },
    { word: "を調べる", choices: ["check", "choose", "claim", "clarify"], answer: "check", example: { en: "Please check your answers before you hand in the test.", ja: "テストを提出する前に答えを確認してください。" } },
    { word: "を選ぶ", choices: ["choose", "claim", "clarify", "clean"], answer: "choose", example: { en: "You have to choose one of the two options.", ja: "2つの選択肢のうち1つを選ばなければならない。" } },
    { word: "と主張する；を要求する", choices: ["claim", "clarify", "clean", "climb"], answer: "claim", example: { en: "He claims to be an expert.", ja: "彼は専門家だと主張している。" } },
    { word: "を明らかにする", choices: ["clarify", "clean", "climb", "close"], answer: "clarify", example: { en: "Could you clarify what you mean?", ja: "あなたの言っていることを明確にしていただけますか？" } },
    { word: "を分類する", choices: ["classify", "clean", "climb", "close"], answer: "classify", example: { en: "The books are classified by author.", ja: "本は著者別に分類されています。" } },
    { word: "をきれいにする", choices: ["clean", "climb", "close", "collect"], answer: "clean", example: { en: "I need to clean my room.", ja: "私は自分の部屋を掃除する必要がある。" } },
    { word: "に登る", choices: ["climb", "close", "collect", "combine"], answer: "climb", example: { en: "He likes to climb mountains.", ja: "彼は山に登るのが好きだ。" } },
    { word: "を閉める", choices: ["close", "collect", "combine", "command"], answer: "close", example: { en: "Please close the door behind you.", ja: "入ったらドアを閉めてください。" } }
];
